version: "3.8"

services:
  dashy-tama-theme:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    # Note: v2.0.8 used as there appears to be authentication bug in current version 2.1.1
    # Authencation is not enabled unless Guest login enabled
    image: lissy93/dashy:2.0.8
    container_name: dashy-tama-theme
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - ./config/conf.yml:/app/public/conf.yml
      - ./themes/user-defined-themes.scss:/app/src/styles/user-defined-themes.scss  # put your custom theme here
    ports:
      - 8020:80
    # Set any environmental variables
    environment:
      - NODE_ENV=production
      # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      - UID=1000
      - GID=1000
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s